name: checkout
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: run application
        run : npm run web & 
              sleep 5 && kill -9 $(pidof node)
      - name: docker build
        run: docker build -t nathirkasim/node:latest .
      - name: docker login 
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && docker push nathirkasim/node:latest
      - name: Deploy to aws ec2
        uses: Castlenine/aws-ssm-command@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          instance-ids: 'i-06a448fb856df07a4'
          commands: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            docker pull nathirkasim/node:latest
            docker stop calculator-app || true
            docker rm calculator-app || true
            docker run -d --name calculator-app -p 3000:3000 nathirkasim/node:latest
